/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btcoban2trongnghia;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class updateFrame extends javax.swing.JFrame {

    dssinhVien dssinhvien;
    DSsinhvienservice dSsinhvienservice;
    DSsinhvienDao dao;
    /**
     * Creates new form updateFrame
     */
    public updateFrame(int masv) throws SQLException{
        
        dSsinhvienservice = new DSsinhvienservice();
        dssinhvien = dSsinhvienservice.getmasv(masv);
        initComponents();
        tentxt.setText(dssinhvien.getTensv());
        mssvtxt.setText(String.valueOf(dssinhvien.getMasv()));
        loptxt.setText(dssinhvien.getLop());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mssvtxt = new javax.swing.JTextField();
        tentxt = new javax.swing.JTextField();
        loptxt = new javax.swing.JTextField();
        capnhatbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("cập nhật thông tin sinh viên");

        jLabel2.setText("masv");

        jLabel3.setText("tên sv");

        jLabel4.setText("lớp");

        capnhatbtn.setText("cập nhật");
        capnhatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatbtnActionPerformed(evt);
            }
        });

        backbtn.setText("back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(capnhatbtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                            .addComponent(backbtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mssvtxt)
                                .addComponent(tentxt)
                                .addComponent(loptxt, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mssvtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tentxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(loptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capnhatbtn)
                    .addComponent(backbtn))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void capnhatbtnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        dssinhvien.setTensv(tentxt.getText());
        dssinhvien.setLop(loptxt.getText());
        
      
        
         try {
             dSsinhvienservice.updatesinhvien(dssinhvien);
         } catch (SQLException ex) {
             Logger.getLogger(addSinhVienFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
       
        
        
         try {
             // TODO add your handling code here:
             new listFramesinhvien().setVisible(true);
         } catch (SQLException ex) {
             Logger.getLogger(addSinhVienFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
       
        this.dispose();
        

    }                                         

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        try {
            // TODO add your handling code here:
            new listFramesinhvien().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(addSinhVienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }                                          

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton capnhatbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField loptxt;
    private javax.swing.JTextField mssvtxt;
    private javax.swing.JTextField tentxt;
    // End of variables declaration//GEN-END:variables
}
